# -*- coding: utf-8 -*-
"""seguimiento.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18y-V8o7mskRjDx_m_8Qya_BgcYC25ta_
"""

import streamlit as st
import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt

# Configuración de la página
st.set_page_config(page_title="Dashboard Financiero", page_icon="📈")

st.title("📈 Dashboard Financiero con yfinance")

# Lista de activos
activos = {
    "Petróleo (BZ=F)": "BZ=F",
    "S&P 500 ETF (SPY)": "SPY",
    "USD/MXN (MXN=N)": "MXN=N",
    "Bimbo (BIMBOA.MX)": "BIMBOA.MX",
    "VIX": "^VIX",
    "Dólar Index (DX-Y.NYB)": "DX-Y.NYB",
    "Bitcoin (BTC-USD)": "BTC-USD"
}

# Selector desplegable
activo_nombre = st.selectbox("Selecciona un activo:", list(activos.keys()))
ticker = activos[activo_nombre]

# Rango de fechas
st.sidebar.header("Configuración")
fecha_inicio = st.sidebar.date_input("Fecha inicio", pd.to_datetime("2024-01-01"))
fecha_fin = st.sidebar.date_input("Fecha fin", pd.to_datetime("today"))

# Descargar datos
data = yf.download(ticker, start=fecha_inicio, end=fecha_fin)

# Validación
if data.empty:
    st.warning("No hay datos disponibles para este activo.")
else:
    st.subheader(f"Precio de cierre - {activo_nombre}")

    # Gráfico
    fig, ax = plt.subplots()
    ax.plot(data.index, data["Close"])
    ax.set_xlabel("Fecha")
    ax.set_ylabel("Precio")
    ax.set_title(f"{ticker}")
    ax.grid()

    st.pyplot(fig)

    # Mostrar datos
    st.subheader("Datos recientes")
    st.dataframe(data.tail())
